version: "3.8"
services:

  jbc-execution:
    container_name: jbc-execution
    image: ethereum/client-go
    user: root
    entrypoint: /root/init-script.sh
    command:
      - "--datadir=/datadir/geth"
      - "--networkid=${NETWORK_ID}"
      - --bootnodes=${EXECUTION_BOOTNODES}
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.vhosts=*
      - --authrpc.jwtsecret=/config/jwt.hex
      - --http
      - --http.addr=0.0.0.0
      - --http.api=eth,engine,erigon,web3,net
      - --http.port=8545
      - --http.corsdomain=*
      - --http.vhosts=*
    volumes:
      - ./genesis.json:/genesis.json
      - ./data:/datadir
      - ./init-script.sh:/root/init-script.sh
      - ./config:/config
    ports:
      - 30303:30303
      - 8545:8545
    restart: always

  jbc-consensus:
    container_name: jbc-consensus
    image: sigp/lighthouse
    user: root
    volumes:
      - ./data/lighthouse:/root/.lighthouse
      - ./config:/config
    ports:
      - 0.0.0.0:9100:9100/tcp
      - 0.0.0.0:9100:9100/udp
    command:
      - lighthouse
      - beacon
      - --execution-endpoint=http://jbc-execution:8551
      - --execution-jwt=/config/jwt.hex
      - --testnet-dir=/config
      - --http-allow-sync-stalled
      - --disable-peer-scoring
      - --http
      - --http-address=0.0.0.0
      - --http-port=5002
      - --disable-packet-filter
      - --eth1
      - --target-peers=${TARGET_PEERS}
      - --enr-address=${NODE_PUBLIC_IP}
      - --enr-udp-port=9100
      - --enr-tcp-port=9100
      - --port=9100
      - --boot-nodes=${BOOTNODE_ENR}
